"""Common field name constants shared across the project."""

ID = "id"
TITLE = "title"
AUTHORS = "authors"
INSTITUTION = "institution"
PUBLISH_DATE = "publish_date"
UPDATE_DATE = "update_date"
CATEGORIES = "categories"
EMBEDDING_VECTOR = "embedding"
PREFERENCE = "preference"
SUMMARY_DATE = "summary_date"
SUMMARY_MODEL = "summary_model"
SCORE = "score"
REASONING_STEP = "reasoning_step"
PROBLEM_BACKGROUND = "problem_background"
METHOD = "method"
EXPERIMENT = "experiment"
ONE_SENTENCE_SUMMARY = "one_sentence_summary"
SLUG = "slug"
KEYWORDS = "keywords"
FURTHER_THOUGHTS = "further_thoughts"
