PAPER_METADATA_TABLE = "paper_metadata"

ID = "id"
SUBMITTER = "submitter"
AUTHORS = "authors"
TITLE = "title"
COMMENTS = "comments"
JOURNAL_REF = "journal_ref"
DOI = "doi"
REPORT_NO = "report_no"
CATEGORIES = "categories"
LICENSE = "license"
ABSTRACT = "abstract"
UPDATE_DATE = "update_date"